helm:
  parameters:
  - name: image.name
    value: 277707114689.dkr.ecr.ap-northeast-2.amazonaws.com/tama-api/order
    forcestring: true
  - name: image.tag
    value: e8cb44ea03ec1028ae6fb35454c0b46f555ac787
    forcestring: true
