helm:
  parameters:
  - name: image.name
    value: 277707114689.dkr.ecr.ap-northeast-2.amazonaws.com/tama-api/order
    forcestring: true
  - name: image.tag
    value: 399602e030fb07dbb235da0c84ed66335dab112a
    forcestring: true
