helm:
  parameters:
  - name: image.name
    value: 277707114689.dkr.ecr.ap-northeast-2.amazonaws.com/tama-api/order
    forcestring: true
  - name: image.tag
    value: 67d59d33615e394d2e9e5a43d09317da81bd4dfc
    forcestring: true
